interface SearchResultProps {
  query: string;
  isSearch?: boolean;
  originalUrl?: string;
  title?: string;
}

export default function SearchResult({
  query,
  isSearch = true,
  originalUrl = "",
}: //title = "",
SearchResultProps) {
  // Mock website content for regular URLs
  const renderWebsiteContent = () => {
    const domain = originalUrl.replace(/^https?:\/\//, "").split("/")[0];

    return (
      <div className="min-h-screen bg-white p-8">
        <div className=" mx-auto">
          {/* Website Header */}
          <div className="border-b border-gray-200 pb-6 mb-8">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">
              Welcome to {domain}
            </h1>
            <div className="flex items-center text-sm text-gray-600">
              <span className="text-green-600 mr-2">●</span>
              <span>{originalUrl}</span>
            </div>
          </div>

          {/* Website Content */}
          <div className="prose prose-lg max-w-none">
            <div className="bg-gray-50 p-6 rounded-lg mb-6">
              <h2 className="text-2xl font-semibold text-gray-800 mb-3">
                This is a custom webview for: {domain}
              </h2>
              <p className="text-gray-600 mb-4">
                Your browser is displaying this website using the custom React
                component instead of a native webview.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              <div className="border border-gray-200 rounded-lg p-4">
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  About This Page
                </h3>
                <p className="text-gray-600 text-sm">
                  This content is generated by your custom browser. The actual
                  website would normally load here, but we're using React
                  components instead.
                </p>
              </div>

              <div className="border border-gray-200 rounded-lg p-4">
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  Features
                </h3>
                <ul className="text-gray-600 text-sm list-disc list-inside space-y-1">
                  <li>Custom rendering engine</li>
                  <li>React-based components</li>
                  <li>Enhanced privacy</li>
                  <li>Better performance</li>
                </ul>
              </div>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
              <h3 className="text-xl font-semibold text-blue-900 mb-2">
                Custom Browser Experience
              </h3>
              <p className="text-blue-800">
                You're viewing this content through your custom React-based
                browser. All websites are displayed using your SearchResult
                component.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Original search results function
  const renderSearchResults = () => {
    const searchResults = [
      {
        title: `${query} - Official Website`,
        url: `https://www.${query.toLowerCase().replace(/\s+/g, "")}.com`,
        description: `Official website for ${query}. Find information, services, and more about ${query}.`,
      },
      {
        title: `${query} - Wikipedia`,
        url: `https://en.wikipedia.org/wiki/${query.replace(/\s+/g, "_")}`,
        description: `Learn about ${query} on Wikipedia. Comprehensive information and history.`,
      },
      {
        title: `About ${query}`,
        url: `https://www.${query.toLowerCase().replace(/\s+/g, "")}info.com`,
        description: `Everything you need to know about ${query}. Features, benefits, and more.`,
      },
    ];

    const relatedSearches = [
      `${query} near me`,
      `${query} prices`,
      `${query} reviews`,
      `best ${query}`,
      `${query} alternatives`,
      `how to use ${query}`,
      `${query} tutorial`,
      `${query} features`,
    ];

    return (
      <div className="min-h-screen bg-white pt-6">
        <div className=" mx-auto px-6">
          {/* Search Stats */}
          <div className="text-gray-500 text-sm mb-8">
            About 124,000,000 results (0.45 seconds) for{" "}
            <strong>"{query}"</strong>
          </div>

          {/* Main Results */}
          <div className="space-y-8">
            {searchResults.map((result, index) => (
              <div key={index} className="group">
                <div className="flex items-center text-xs mb-1">
                  <div className="w-3 h-3 bg-green-500 rounded-full mr-2"></div>
                  <span className="text-gray-500">{result.url}</span>
                </div>
                <a
                  href={result.url}
                  className="text-blue-600 hover:underline text-lg font-medium block mb-2 group-hover:text-blue-800 leading-tight"
                >
                  {result.title}
                </a>
                <p className="text-gray-700 text-sm leading-relaxed">
                  {result.description}
                </p>
              </div>
            ))}
          </div>

          {/* Related Searches */}
          <div className="mt-12">
            <h3 className="text-lg font-medium text-gray-900 mb-6">
              Related searches
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {relatedSearches.map((search, index) => (
                <div
                  key={index}
                  className="flex items-center p-3 hover:bg-gray-50 rounded-lg group cursor-pointer"
                >
                  <div className="flex items-center w-full">
                    <svg
                      className="w-4 h-4 text-gray-400 mr-3"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                      />
                    </svg>
                    <span className="text-gray-700 text-sm group-hover:text-gray-900">
                      {search}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Pagination */}
          <div className="flex justify-center mt-12 mb-8">
            <div className="flex items-center space-x-1">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((num) => (
                <button
                  key={num}
                  className={`w-8 h-8 flex items-center justify-center text-sm rounded hover:bg-gray-200 ${
                    num === 1 ? "text-blue-600 font-medium" : "text-gray-700"
                  }`}
                >
                  {num}
                </button>
              ))}
              <button className="text-blue-600 text-sm hover:underline ml-2 px-2">
                Next
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // Render either website content or search results
  return isSearch ? renderSearchResults() : renderWebsiteContent();
}
